name: ğŸ› Bug Report
description: Create a bug report to help us reproduce and fix the bug

body:
  - type: markdown
    attributes:
      value: >
        #### Before submitting a bug, please make sure the issue hasn't been already reported/addressed by searching through [the
        existing and past issues](https://github.com/pytorch/tau/issues), the [README](https://github.com/pytorch/tau/blob/main/README.md).
        
  - type: textarea
    attributes:
      label: ğŸ› Describe the bug
      description: |
        Please provide a clear and concise description of what the bug is.

        If relevant, please provide a minimal example so that we can reproduce the error by running the code. 
        
      placeholder: |
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error logs
      description: |
       Paste the error logs that indicate the problem

      placeholder: |
        Error...

    validations:
      required: true

  - type: textarea
    attributes:
      label: Enviroment
      description: |
        Please provide infromation about your running enviroment
      placeholder: |
        PyTorch env info: python -m "torch.utils.collect_env"    
    validations:
      required: true
    

  - type: textarea
    attributes:
      label: Settings
      description: |
        Please provide your running settings
      placeholder: |
       Number of Nodes :
       Number of GPU per Node: 
       scheduler : 
    validations:
      required: true 

  - type: textarea
    attributes:
      label: Possible Solution
      description: |
        Possible fix for them the problem

  - type: markdown
    attributes:
      value: >
        Thanks for contributing ğŸ‰!
